### ISSUE TITLE
Execute tasks irrespective of default branch name

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyllbot#10]
Crossposting from https://github.com/jekyll/maintainers/issues/63#issuecomment-1100031133 for greater visibility:

> Couple of issues encountered with  `jekyll/jekyll-avatar`:
> - JekyllBot doesn't update History.markdown automatically.
> - JekyllBot doesn't create GitHub release automatically.

*Context: The default branch at `jekyll/jekyll-avatar` is `main` instead of `master`*

**Comment by parkr** [comment]
I just hit this with jekyll/github-metadata. There are a number of places we assume `master` instead of `main`.

**Comment by parkr** [comment]
Still works on repos with `master`: https://github.com/jekyll/teams/pull/13

Works for `main` now too! https://github.com/jekyll/github-metadata/pull/236

**Comment by ashmaroli** [comment]
Awesome! Thanks for addressing this @parkr
