### ISSUE TITLE
Close stale issues as "not planned"

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyllbot#14]
GitHub recently enhanced their issues feature with [*closed reasons*](https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/), with the default reason being `complete`.

When JekyllBot closes stale issues, they get `complete` as the reason instead of `not planned` as GitHub expects.

It would be great if JekyllBot would provide the correct reason via the dispatch webhook.

**Comment by parkr** [comment]
This requires an upgrade to go-github which I did in #18, but when I went looking for this in the API, it [doesn't appear to be present](https://docs.github.com/en/rest/issues/issues#update-an-issue). Do you know if there is API support for this feature?

**Comment by parkr** [comment]
I emailed GitHub Support about this.

**Comment by parkr** [comment]
I added this in https://github.com/google/go-github/pull/2395. Once it’s released (if not already), then we can pull it in!

**Comment by parkr** [comment]
Looks like we need to upgrade to v46, then change the request to set this field.
